services:
  - type: web
    name: planning-poker
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: CLIENT_URL
        value: https://planning-poker.onrender.com
    healthCheckPath: /
    autoDeploy: true

